# Generated by Django 2.1 on 2019-06-16 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('sms_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
