# Generated by Django 2.1 on 2019-06-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_notifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'User Details', 'verbose_name_plural': 'User Details'},
        ),
    ]
