# Generated by Django 2.1 on 2019-06-30 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_notifier', '0002_auto_20190616_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('1', 'whatsapp'), ('2', 'email'), ('3', 'sms')], default='1', max_length=50)),
                ('message_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logged_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'name not present'), ('2', 'file not present'), ('3', 'no. not in contacts'), ('4', 'queued'), ('5', 'success')], max_length=20)),
                ('group', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappMessagesToSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('1', 'name not present'), ('2', 'file not present'), ('3', 'no. not in contacts'), ('4', 'queued'), ('5', 'success')], max_length=20)),
                ('path', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='sms_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')]),
        ),
    ]
